### ISSUE TITLE
yarn example is not invoked in CI

### ISSUE THREAD

**Issue by stepancheg** [satya164/react-simple-code-editor#70]
`example` is not mentioned in `.circleci` or `.github` folders.

And locally `yarn example` fails on my laptop with:

```
% yarn example
yarn run v1.22.4
$ parcel example/index.html
(node:9237) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/build/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/build/Debug/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/build/Release/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/out/Debug/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/Debug/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/out/Release/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/Release/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/build/default/deasync.node
 → /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/compiled/14.3.0/darwin/x64/deasync.node
    at bindings (/Users/nga/devel/left/react-simple-code-editor/node_modules/bindings/bindings.js:88:9)
    at /Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/Users/nga/devel/left/react-simple-code-editor/node_modules/deasync/index.js:76:2)
    at Module._compile (/Users/nga/devel/left/react-simple-code-editor/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/nga/devel/left/react-simple-code-editor/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/nga/devel/left/react-simple-code-editor/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9237) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.30s.
```

(And no files created anywhere)

Without CI it's not clear, is it a problem with my setup or with the repo.

**Comment by holub008** [comment]
I'm really not familiar with this project's framework / development stack, but running
```sh
npm install --only=dev deasync
```

from project root solved this problem for me. I'm not sure why this works (is it just a missing listed dependency? platform dependent?), or how harmful it may be to the development environment.

**Comment by Arunkanagu** [comment]
[Error - 11:33:13 am] Failed to load jshint library
(node:5520) UnhandledPromiseRejectionWarning: Error: Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then reload.
    at Linter.<anonymous> (c:\Users\User\.vscode\extensions\dbaeumer.jshint-0.11.0\jshint-server\out\server.js:336:23)
    at Generator.throw (<anonymous>)
    at rejected (c:\Users\User\.vscode\extensions\dbaeumer.jshint-0.11.0\jshint-server\out\server.js:9:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 102)

hoe to fix this.....?
